receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
    spike_limit_mib: 64
  resource:
    attributes:
      - action: insert
        key: service.environment
        value: ${env:NODE_ENV}

exporters:
  prometheus:
    endpoint: "0.0.0.0:8888"
    namespace: regx
  logging:
    verbosity: normal
  # Add Jaeger / Tempo in production
  # jaeger:
  #   endpoint: jaeger:14250
  #   tls:
  #     insecure: true

service:
  pipelines:
    traces:
      receivers:  [otlp]
      processors: [memory_limiter, batch, resource]
      exporters:  [logging]
    metrics:
      receivers:  [otlp]
      processors: [memory_limiter, batch]
      exporters:  [prometheus]
    logs:
      receivers:  [otlp]
      processors: [memory_limiter, batch]
      exporters:  [logging]
